layout_spectrum: 1
color:
  saturation: 0.5454174
  brandStrength: 1
  lightness: 0.1511298
  brandColors:
    - '#8090AA'
    - '#BFCCDC'
    - '#575759'
    - '#C44E04'
    - '#743E29'
  rhythmicContrast: 0.5679106
typography_spectrum: 0.3502506
name: Pilkkireissu 2016
